name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.0-rc.1'
      - name: Set Go Environment Variables
        run: |
            echo "${HOME}/go/bin" >> $GITHUB_PATH
      - name: Setup Cache 
        uses: actions/cache@v2
        with:
          path: |
            ${HOME}/go/pkg/mod
            ${HOME}/.cache/go-build
            ${HOME}/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: 🔨 Install Dependencies 🔨
        run: make install
      - name: 🚀 Deploy 🚀 
        run: make deploy 
        env:
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      - name: ⏰ Bump version and push tag ⏰
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ steps.tag_version.outputs.new_tag }}
          prerelease: false
          files: |
            LICENSE
            dist/*
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          files: |
            LICENSE
            dist/*
