apiVersion: v1
kind: Service
metadata:
  name: recipe-db
  labels:
    app: recipe-db
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30050
      name: recipe-db
  selector:
    app: recipe-db
