# function install_node_red_plugins() {
#   NODE_RED_POD=$(kubectl -n geck get pod -l app=node-red -o jsonpath="{.items[0].metadata.name}")
#   # kubectl -n geck exec -it "$NODE_RED_POD" -- /bin/bash -c "mkdir -p /data/.npm && chown -R 1000:1000 /data/.npm"

#   if ! kubectl -n geck exec -it "$NODE_RED_POD" -- /bin/bash -c "npm list node-red-node-twilio" &> /dev/null; then
#     echo "Installing node-red dependencies..."
#     kubectl -n geck exec -it "$NODE_RED_POD" -- /bin/bash -c "npm install node-red-node-twilio"
#   fi
# }
---
apiVersion: v1
kind: Service
metadata:
  name: node-red
  namespace: geck
spec:
  selector:
    app: node-red
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1880
      name: node-red
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red
  namespace: geck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      containers:
        - name: node-red
          image: nodered/node-red:2.2.3
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 1880
              protocol: TCP
          env:
            - name: TZ
              value: "${TIMEZONE}"
          volumeMounts:
            - name: node-red-data-volume
              mountPath: /data
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
      volumes:
        - name: node-red-data-volume
          hostPath:
            path: ${NODERED_BASE_DIRECTORY}/data