---
apiVersion: v1
kind: Service
metadata:
  name: octoprint-server
  namespace: geck
spec:
  selector:
    app: octoprint-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31553
      name: octoprint-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: octoprint-server
  namespace: geck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: octoprint-server
  template:
    metadata:
      labels:
        app: octoprint-server
    spec:
      nodeSelector:
        type: 3dprinter
      tolerations:
        - key: "type"
          value: "3dprinter"
          effect: "NoSchedule"
      dnsPolicy: "Default"
      containers:
      - name: octoprint-server
        image: octoprint/octoprint:1.8.7
        ports:
          - containerPort: 80
            protocol: TCP
        env:
          - name: ENABLE_MJPG_STREAMER
            value: 'false'
        securityContext:
          privileged: true
        resources:
          requests:
            memory: 750Mi
            cpu: 300m
          limits:
            memory: 1500Mi
        volumeMounts:
          - name: octoprint-server-data-volume
            mountPath: /octoprint
            readOnly: false
          - name: ttyama0
            mountPath: /dev/dev/ttyAMA0
            readOnly: false
          - name: video0
            mountPath: /dev/video0
            readOnly: false
      volumes:
        - name: octoprint-server-data-volume
          hostPath:
            path: ${OCTOPRINT_BASE_DIRECTORY}
        - name: ttyama0
          hostPath:
            path: /dev/dev/ttyAMA0
        - name: video0
          hostPath:
            path: /dev/video0