apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  selector:
    app: discovery-service
  clusterIP: None
  ports:
    - name: discovery-service
      port: 8761
      targetPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service-lb
spec:
  selector:
    app: discovery-service
  type: LoadBalancer
  ports:
    - name: discovery-service
      port: 8761