name: Testing iOS 14.4
on: [push]

jobs:
  ship_it:
    runs-on: macos-11
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.4'
      - name: 🚀 Run UI Tests 🚀
        run: make run_passing_ui_tests
