highlighter: rouge
markdown: kramdown
permalink: /archives/:title/
gems: [jekyll-paginate]
url: http://www.tjmaynes.com
author: TJ Maynes
port: 4000
github_user: tjmaynes
timezone: America/New York
paginate: 3
paginate_path: "page:num"
