version: '3.1'

services:
  recipe-book-db:
    image: "postgres:11.5-alpine"
    restart: always
    volumes:
      - recipe-book-volume:/var/lib/postgresql/data/
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - recipe-book-network
    ports:
      - "5432:5432"
    env_file: ".env.development"

volumes:
  recipe-book-volume:

networks:
  recipe-book-network: