apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      name: gateway-service
