version: '3.3'

volumes:
  nextcloud_web:
    driver: local
  nextcloud_db:
    driver: local
  nextcloud_redis:
    driver: local

networks:
  nextcloud:
    external: false

services:
  app:
    image: nextcloud:24.0.2
    container_name: nextcloud-web
    restart: always
    ports:
      - 8080:80
    links:
      - db
    networks:
      - nextcloud
    volumes:
      - nextcloud_web:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - POSTGRES_USER=${NEXTCLOUD_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DATABASE_PASSWORD}
      - POSTGRES_DB=${NEXTCLOUD_DATABASE}
      - POSTGRES_HOST=db
      - REDIS_HOST=redis

  db:
    image: postgres:14
    container_name: nextcloud-db
    restart: always
    ports:
      - ${NEXTCLOUD_DATABASE_PORT}:5432
    environment:
      - POSTGRES_USER=${NEXTCLOUD_USER}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DATABASE_PASSWORD}
    networks:
      - nextcloud
    volumes:
      - nextcloud_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${NEXTCLOUD_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0.2
    container_name: nextcloud-redis
    restart: always
    ports:
      - ${NEXTCLOUD_REDIS_PORT}:6379
    networks:
      - nextcloud
    volumes:
      - nextcloud_redis:/var/lib/redis
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 5s
      retries: 5
