name: CI

on:
  push:
    branches:
      - main

jobs:
  ship_it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: Cache rust dependencies
        uses: Swatinem/rust-cache@v1
      - name: 🔨 Install Dependencies 🔨
        run: sudo apt-get update && sudo apt-get install make && make install
      - name: 🧪 Test 🧪
        run: make test
